import { mkdir, writeFile, stat } from 'node:fs/promises';
import { createReadStream } from 'node:fs';
import path from 'node:path';
import crypto from 'crypto';

/**
 * Small public images (course marketing thumbnails) stored on the server's
 * own disk and served back through the API.
 *
 * Deliberately NOT Bunny: Bunny Stream hosts lesson video, and Bunny Storage
 * is a separate product needing its own zone. A handful of small, rarely
 * changing marketing images don't justify that dependency.
 *
 * Backed by a Docker volume so uploads survive container rebuilds.
 */
const UPLOAD_DIR = process.env['UPLOAD_DIR'] ?? '/app/uploads';
const IMAGES_SUBDIR = 'images';

// Filenames are generated by us (uuid.ext). Anything not matching this exact
// shape is rejected before touching the filesystem — the only thing standing
// between a user-supplied path segment and traversal outside the upload dir.
const SAFE_NAME = /^[0-9a-f-]{36}\.(jpg|png|webp)$/;

export const EXT_BY_MIME: Record<string, string> = {
  'image/jpeg': 'jpg',
  'image/png': 'png',
  'image/webp': 'webp',
};

const MIME_BY_EXT: Record<string, string> = {
  jpg: 'image/jpeg',
  png: 'image/png',
  webp: 'image/webp',
};

function imagesDir(): string {
  return path.join(UPLOAD_DIR, IMAGES_SUBDIR);
}

/** Writes the image and returns its generated filename. */
export async function saveImage(buffer: Buffer, ext: string): Promise<string> {
  const dir = imagesDir();
  await mkdir(dir, { recursive: true });
  const filename = `${crypto.randomUUID()}.${ext}`;
  await writeFile(path.join(dir, filename), buffer);
  return filename;
}

/**
 * Resolves a request filename to an on-disk path, or null when the name is
 * malformed / the file is missing. Never interpolates raw input into a path.
 */
export async function resolveImage(
  filename: string,
): Promise<{ stream: NodeJS.ReadableStream; contentType: string; size: number } | null> {
  if (!SAFE_NAME.test(filename)) return null;

  const full = path.join(imagesDir(), filename);
  // Belt-and-braces: confirm the resolved path really is inside the dir.
  if (!full.startsWith(imagesDir() + path.sep)) return null;

  try {
    const info = await stat(full);
    if (!info.isFile()) return null;
    const ext = filename.split('.').pop()!;
    return {
      stream: createReadStream(full),
      contentType: MIME_BY_EXT[ext] ?? 'application/octet-stream',
      size: info.size,
    };
  } catch {
    return null;
  }
}
